import React from 'react';
import { motion } from 'framer-motion';
import { BrainCircuit, CheckCircle2, AlertCircle, Info } from 'lucide-react';

const AIInsightPanel = ({ insights }) => {
  // Fallback insights if none provided
  const defaultInsights = [
    { text: "Your consistent assessment scores indicate high material retention.", type: 'success' },
    { text: "Late registrations historically correlate with higher withdrawal risk; foundational focus recommended.", type: 'warning' },
    { text: "VLE engagement peaks on weekends; study plan optimized for high-intensity Saturday sessions.", type: 'info' }
  ];

  const displayInsights = insights || defaultInsights;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="p-8 bg-slate-900/40 border border-slate-800 rounded-3xl backdrop-blur-sm"
    >
      <div className="flex items-center gap-3 mb-8">
        <BrainCircuit className="w-6 h-6 text-indigo-400" />
        <h3 className="text-xl font-bold text-white tracking-tight">AI Reasoning & Optimization</h3>
      </div>

      <div className="space-y-6">
        {displayInsights.map((insight, idx) => (
          <div key={idx} className="flex gap-4 group">
            <div className="mt-1">
              {insight.type === 'success' && <CheckCircle2 className="w-5 h-5 text-emerald-500" />}
              {insight.type === 'warning' && <AlertCircle className="w-5 h-5 text-amber-500" />}
              {insight.type === 'info' && <Info className="w-5 h-5 text-blue-500" />}
            </div>
            <div>
              <p className="text-slate-300 group-hover:text-white transition-colors duration-200">
                {insight.text}
              </p>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 p-4 bg-indigo-500/5 rounded-xl border border-indigo-500/10">
        <p className="text-xs text-slate-500 italic text-center">
          Insights generated by Ensemble Stacking Model (XGBoost + LightGBM)
        </p>
      </div>
    </motion.div>
  );
};

export default AIInsightPanel;
